services:
  app-dev:
    build: 
      context: ./app
      target: dev
    ports:
      - "8080:5173"
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      - VITE_POCKETBASE_URL=http://pocketbase:8080
    depends_on:
      - pocketbase
    networks:
      - mealnet
    profiles: ["dev"]

  app-prod:
    build:
      context: ./app
      target: prod
    ports:
      - "8080:80"
    environment:
      - VITE_POCKETBASE_URL=http://pocketbase:8080
    depends_on:
      - pocketbase
    networks:
      - mealnet
    profiles: ["prod"]

  pocketbase:
    build: ./pb
    restart: unless-stopped
    ports:
      - "8090:8080"
    volumes:
      - ./pb_data:/pb/pb_data
      - ./pb/pb_migrations:/pb/pb_migrations
    networks:
      - mealnet

networks:
  mealnet:
